### ISSUE TITLE
 DeserializationError: Deserialization error: Wrong directory fields and Certificate dose not generate.

### ISSUE THREAD

**Issue by tanutapi** [dtsepelev/meteor-up-letsencrypt#2]
Got error in letsencrypt-companion:
`2016-12-12 14:36:41,717:INFO:simp_le:1211: Generating new account key
2016-12-12 14:36:42,533:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1401, in main
    return main_with_exceptions(cli_args)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1386, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1282, in persist_new_data
    client = registered_client(args, existing_data.account_key)
  File "build/bdist.linux-x86_64/egg/simp_le.py", line 1224, in registered_client
    client = acme_client.Client(directory=args.server, key=key, net=net)
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "build/bdist.linux-x86_64/egg/acme/messages.py", line 169, in from_json
    raise jose.DeserializationError(str(error))
DeserializationError: Deserialization error: Wrong directory fields

Unhandled error has happened, traceback is above`

There is also open issues on
[JrCS/docker-letsencrypt-nginx-proxy-companion - Issue 131](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/131)

**Comment by dtsepelev** [comment]
@tanutapi Thanks for sharing. Here is another related [issue](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/130). Looks like JrCs is not maintaining his repo anymore (at least he didn't merge the fix yet), but I will wait for a few days to see if anything will change. Otherwise, I will replace it with a working fork.

**Comment by rcmpayne** [comment]
@dtsepelev any update on this? i am trying to use this docker on unraid and getting the same issues. forst time setup.

**Comment by dtsepelev** [comment]
@rcmpayne @tanutapi replaced docker companion with a working fork by alastaircoote `alastaircoote/docker-letsencrypt-nginx-proxy-companion`. Please pay attention that it is replaced only for meteor-1.4 branch. You should update your npm package with `npm update -g mupx-letsencrypt@meteor14`
